Add debugging changes

diff --git a/.github/workflows/aws-main.yml b/.github/workflows/aws-main.yml
--- a/.github/workflows/aws-main.yml
+++ b/.github/workflows/aws-main.yml
@@ -193,7 +193,7 @@ jobs:
     name: "Push images"
     runs-on: ubuntu-latest
     # push image on main, target branch not set, and the dependent steps were either successful or skipped
-    if: ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') ) && !failure() && !cancelled() && github.repository == 'localstack/localstack'
+    if: ( github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') ) && !failure() && !cancelled()
     needs:
       # all tests need to be successful for the image to be pushed
       - test
@@ -209,18 +209,18 @@ jobs:
         with:
           platform: ${{ env.PLATFORM_NAME_AMD64 }}
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1
+      #- name: Configure AWS credentials
+      #  uses: aws-actions/configure-aws-credentials@v4
+      #  with:
+      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      #    aws-region: us-east-1
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-        with:
-          registry-type: public
+      #- name: Login to Amazon ECR
+      #  id: login-ecr
+      #  uses: aws-actions/amazon-ecr-login@v2
+      #  with:
+      #    registry-type: public
 
       - name: Push ${{ env.PLATFORM_NAME_AMD64 }} Docker Image
         env:
@@ -229,9 +229,9 @@ jobs:
           PLATFORM: ${{ env.PLATFORM_NAME_AMD64 }}
         run: |
           # Push to Docker Hub
-          ./bin/docker-helper.sh push
+          TARGET_IMAGE_NAME="agihi/localstack" ./bin/docker-helper.sh push
           # Push to Amazon Public ECR
-          TARGET_IMAGE_NAME="public.ecr.aws/localstack/localstack" ./bin/docker-helper.sh push
+          # TARGET_IMAGE_NAME="public.ecr.aws/localstack/localstack" ./bin/docker-helper.sh push
 
       - name: Load Localstack ${{ env.PLATFORM_NAME_ARM64 }} Docker Image
         uses: ./.github/actions/load-localstack-docker-from-artifacts
@@ -245,9 +245,9 @@ jobs:
           PLATFORM: ${{ env.PLATFORM_NAME_ARM64 }}
         run: |
           # Push to Docker Hub
-          ./bin/docker-helper.sh push
+          TARGET_IMAGE_NAME="agihi/localstack" ./bin/docker-helper.sh push
           # Push to Amazon Public ECR
-          TARGET_IMAGE_NAME="public.ecr.aws/localstack/localstack" ./bin/docker-helper.sh push
+          # TARGET_IMAGE_NAME="public.ecr.aws/localstack/localstack" ./bin/docker-helper.sh push
 
       - name: Push Multi-Arch Manifest
         env:
@@ -255,20 +255,20 @@ jobs:
           DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
         run: |
           # Push to Docker Hub
-          ./bin/docker-helper.sh push-manifests
+          IMAGE_NAME="agihi/localstack" ./bin/docker-helper.sh push-manifests
           # Push to Amazon Public ECR
-          IMAGE_NAME="public.ecr.aws/localstack/localstack" ./bin/docker-helper.sh push-manifests
+          # IMAGE_NAME="public.ecr.aws/localstack/localstack" ./bin/docker-helper.sh push-manifests
 
-      - name: Publish dev release
-        env:
-          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
-          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
-        run: |
-          if git describe --exact-match --tags >/dev/null 2>&1; then
-            echo "not publishing a dev release as this is a tagged commit"
-          else
-            make install-runtime publish || echo "dev release failed (maybe it is already published)"
-          fi
+      #- name: Publish dev release
+      #  env:
+      #    TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
+      #    TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
+      #  run: |
+      #    if git describe --exact-match --tags >/dev/null 2>&1; then
+      #      echo "not publishing a dev release as this is a tagged commit"
+      #    else
+      #      make install-runtime publish || echo "dev release failed (maybe it is already published)"
+      #    fi
 
   push-to-tinybird:
     name: Push Workflow Status to Tinybird
